### PR TITLE
Maintentance/update to python37 follow up

### PR DESCRIPTION
**Pull request by gro1m**
remove object everywhere as new-style classes inherit by default from object in Python3 as discussed in PR #124

### CODE REVIEW

**Comment by aconrad** [comment]
This is great, thank you! I'll merge it after your big PR is merged, I don't want to risk introducing conflicts on the big one.

**Comment by aconrad** [comment]
As expected, this now conflicts but it should be trivial to fix. 👍

**Comment by gro1m** [comment]
> As expected, this now conflicts after merging #124 but it should be trivial to fix. 👍

Yes, fixed :)

**Comment by aconrad** [comment]
Thanks!!

**Pull request merged**
