### PR TITLE
handle multiple classes in the same file, Fixes #112 

### LINKED ISSUE #112: Multiple classes in the same file are ignored
It looks like if a cobertura report has multiple classes in the same file, only the first class will populate the stats for that file and the others will be ignored. 
[coverageExample.zip](https://github.com/aconrad/pycobertura/files/6131849/coverageExample.zip)

### PR DESCRIPTION
**Pull request by smortvedt**
I tried to add this feature while minimally changing the other features. I very new to this project so please review carefully as I just tested a few different cases. Fixes #112

### CODE REVIEW

**Comment by gro1m** [comment]
Hi @aconrad @smortvedt 
This is a mistake that we should fix.

Could you (@smortvedt)  fix this maybe using the newest Python 3.7 possibilities, i.e. f-strings et cetera in cobertura.py. In addition, one has to change the testing checks in cli.py that fail according to the TRAVIS CI output:
https://app.travis-ci.com/github/aconrad/pycobertura/jobs/490695222#L400-L484.

The mistake is apparent when looking at `tests/cobertura.xml`: one sees that the statistics from lines 52-70 from the second class with ""Main$Helper" are not included, i.e. lines with numbers from 31-34 and thus there should also be 15 instead of 11 statements...

I could also do this, but @smortvedt would need to give me developer rights on his master branch if I were to do it in this PR. Otherwise, I'd need to pull the branch separately and integrate it into my fork and work from there...

**Comment by aconrad** [comment]
This totally fell through the cracks, I'm sorry about that. I'll try to take a look at this proposal this week.

**Comment by aconrad** [comment]
@smortvedt any chance we can merge the latest code from master into your branch?

**Comment by aconrad** [comment]
Closing this PR in favor of #132 where it's being revived. Thanks @smortvedt for your work here!

**Pull request closed without merging**
