### PR TITLE
chore: blacken the code base

### PR DESCRIPTION
**Pull request by nilleb**
Integrate [black](https://github.com/psf/black) to format sources.

The base of this pull request should be the `feat/versioned-cobertura` in order to avoid conflicts on merge.

### CODE REVIEW

**Comment by aconrad** [comment]
I will review this PR once we get https://github.com/aconrad/pycobertura/pull/94 merged.

**Comment by nilleb** [comment]
@aconrad here you can find a commodity pull request showing the changes made by black, and only them: https://github.com/nilleb/pycobertura/pull/1

**Comment by aconrad** [comment]
Hey @nilleb, I took the freedom to resolve the merge conflict but Travis still fails. Can you take a look?

**Comment by nilleb** [comment]
@aconrad fixed! you will find an explanation of why it was failing on https://travis-ci.community/t/black-cannot-be-installed-with-python-3-5/1627
I have added this link to the commit message, as well.

Good night!

**Comment by aconrad** [comment]
Awesome, thanks @nilleb! Great work on this, thanks for submitting this PR!

**Pull request merged**
