### PR TITLE
Maintenance refactor and update code

### PR DESCRIPTION
**Pull request by gro1m**
Hi @aconrad 

As stated in https://github.com/aconrad/pycobertura/issues/120, I refactored the project's code to make it up-to-date with the current Python versions.
I tested locally with Python version 3.9 and all 112 tests passed.
I ended up making more (aggressive) changes than I originally thought I would, but I still hope you will enjoy reviewing this PR and I am looking forward to your ideas, suggestions, questions, et cetera...

### CODE REVIEW

**Comment by gro1m** [comment]
Hi @aconrad 

I think I am good now for the time-being and would appreciate your input especially on the following points:
1) travis ci pipeline build does not seem to be triggered automatically.
2) setup.py vs. setup.cfg and pyproject.toml - the latter is the new standard, which I thought I'd incorporate here. Leaves though a TODO still for release.sh as I need to write a config parser (but then you really can read out any information from the setup.cfg file)
3) I might still change the row-wise logic to a column-wise logic and then named tuples for dictionaries which would make the JSON reporter implementation probably quite straightforward. If you have any inputs on this that'd be great :)

And of course, I generally wonder on how happy you are with the changes I introduced in this PR:)

**Comment by aconrad** [comment]
Thank you for this PR. I'll try to take a look at it this weekend.

**Comment by gro1m** [comment]
Thanks @aconrad

For your understanding this PR contains the following parts:

**1. update to Python >=3.7**
- `.travis.yml` (also corrected formatting with Visual Studio Code IDE)
- `tox.ini`
- `setup.cfg`: adapt classifiers
        
**2. shift from setup.py to setup.cfg**
- `setup.cfg`
- `pyproject.toml` (setuptools >=51 to use entry_points in setup.cfg, pip restriction I am not sure)
- deleted `setup.py` (deprecated use of pypandoc because markdown is natively supported by PyPI by now)
 - renamed `LICENSE.txt` to `LICENSE`
 - STILL TODO:
      - `release.sh` would need to be adapted:
      - especially a `setup.cfg` parser using Python’s configparser package would need to be written.

**linting/renicening**
- `.gitignore`: add .DS_Store for people developing with MacOS
- `README.md`: apply markdown linting suggestions by VS Code :
     - everything with $ should also show output
     - images should have an alternate text.
     - specify a language for every ``` ```block.
     - no inline html was ignored as there seems no possibility to specify image width in native markdown.
             
**refactoring reporters**
- `reporters.py`: 
    - use tuple comprehensions
    - use list comprehensions
    - use f-strings (allowed since Python 3.6)
    - do formatting of missed lines and line rate directly in Reporter `get_report_lines` function simplifying both TextReporter and HTMLReporter class.
    - tried to simplify DeltaReporter classes as well but they are harder.
- `utils.py`:
    - write utils function stringify to allow to format missed lines in Reporter class directly
    - use f-strings (allowed since Python 3.6)
 - `tests/test_stringify.py`
     - write tests for stringify method in analogy to rangify method.

Depending on the results of your review, it may be possible to split this into separate PRs that build on each other.

**Comment by aconrad** [comment]
@gro1m thanks for all you do, much appreciated! 🙏

As suggested, can you please split pycobertura packaging changes (your paragraphs 1. 2. and 3.) in their own PR, separate from the changes related to the library (paragraph 4.).

> `release.sh` would need to be adapted

We will need to get this script working, that's what I use to make releases and I don't release often enough to remember how they work. If this doesn't work I'm going to be lost 😂

I still need to take a deeper look at the changes, but I wanted to provide some early feedback on splitting into smaller PRs, it would help and allow PR to be merged independently. Would that work for you?

**Comment by aconrad** [comment]
Also, I don't know why Travis doesn't kick off the tests. When I log into Travis, I get this message:

Screen Shot 2022-01-08 at 12 04 12 AM

I don't understand because I'm using a free plan... Time to look for another provider? It seems that every time a PR is submitted, Travis doesn't build for different reasons. This has been annoying.

In the meantime, I sent an email to their support team.

**Comment by gro1m** [comment]
Hi @aconrad 
I split this into:
- https://github.com/aconrad/pycobertura/pull/123 
- https://github.com/aconrad/pycobertura/pull/124

thanks to git's cherry-picking, interactive rebasing and merge conflict resolution mechanisms :)

**Comment by gro1m** [comment]
With regards to the CI, you might want to try GitHub actions with CircleCI. I did not try yet, but for GitHub repos seems to be a good plan :)

**Comment by gro1m** [comment]
PR descriptions updated and `release.sh` should be adapted now and I am quite confident that it works, though I could not test it (theoretically we could have a CI step to prepublish to testpypi and then do some import tests before publishing to PyPI)

**Comment by aconrad** [comment]
Can you retrigger the PRs? I got some Travis credit, let's see if it works...

**Comment by aconrad** [comment]
I think it's safe to close this PR now.

**Pull request closed without merging**
